### ISSUE TITLE
Not able to deploy  PNDA using  previous releases of platform-salt for online deployment.

### ISSUE THREAD

**Issue by chandanpal** [pndaproject/pnda-cli#44]
pnda-env.yaml file has the key PLATFORM_GIT_BRANCH to deploy specific branch of platform-salt but not supporting release TAG so how can we deploy PNDA using specific release of  platform-salt for the online deployment?

**Comment by trsmith2** [comment]
Branch has the same meaning as 'branch' in the git documentation here i.e. you can pass what you might pass to clone or checkout, which would include tags.
